# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                ProjectStaff_1_8 - V1.0                                       | #
# |                             mc.creabyte.es - sakurapvp.club                                  | #
# |                                Plugin developed by Hqwks.                                    | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

############################################################
# +------------------------------------------------------+ #
# |              DataBase - Configuration                | #
# +------------------------------------------------------+ #
############################################################

MySQL:
  Host: localhost
  Port: 3306
  DataBase: 'MyDataBase'
  Username: 'MyUsername'
  Password: 'MyPassword'